window.defaultContent = {
    "credentials": {
        "email": "admin@duhohratky.cz",
        "password": "admin123"
    },
    "news": {
        "title": "Aktuálně u nás",
        "subtitle": "Co se chystá",
        "items": [
            {
                "id": "news_1707123456789",
                "date": "2024-02-14",
                "title": "Valentýnské tvoření",
                "text": "Přijďte si vyrobit originální přáníčka a dárky pro své milované. Dílnička vhodná pro děti od 3 let.",
                "tag": "free_spots"
            }
        ]
    },
    "hero": {
        "badge": "✨ Kreativita & Rozvoj",
        "title": "Vítejte v",
        "titleHighlight": "Duhohrátkách",
        "subtitle": "Sensory play & Montessori aktivity pro rozvoj vašich dětí",
        "description": "Objevte svět hravého učení, kde se děti rozvíjejí prostřednictvím smyslových her, kreativních činností a Montessori přístupu v bezpečném a inspirujícím prostředí.",
        "stat1Number": "500+",
        "stat1Label": "Šťastných dětí",
        "stat2Number": "20+",
        "stat2Label": "Typů aktivit",
        "stat3Number": "8+",
        "stat3Label": "Let praxe",
        "stat4Number": "5⭐",
        "stat4Label": "Hodnocení",
        "btn1Text": "📅 Rezervovat termín",
        "btn1Link": "#reservation",
        "btn2Text": "🎨 Prozkoumat aktivity",
        "btn2Link": "#activities"
    },
    "about": {
        "title": "Co jsou Duhohratky?",
        "card1Icon": "🎨",
        "card1Title": "Sensory Play",
        "card1Text": "Smyslové hry, které rozvíjejí hmat, čich, zrak i sluch. Děti objevují textury, barvy a zvuky v bezpečném prostředí.",
        "card2Icon": "📚",
        "card2Title": "Montessori přístup",
        "card2Text": "Respektujeme individualitu každého dítěte. Učíme se hrou, pozorováním a vlastním tempem objevování světa.",
        "card3Icon": "🧠",
        "card3Title": "Rozvoj dovedností",
        "card3Text": "Podpora jemné motoriky, koordinace, koncentrace a kreativního myšlení prostřednictvím zábavných aktivit.",
        "card4Icon": "💕",
        "card4Title": "Bezpečné prostředí",
        "card4Text": "Všechny materiály jsou bezpečné a netoxické. Prostory jsou přizpůsobené potřebám malých objevitelů.",
        "storyTitle": "Náš příběh",
        "storyText": "Duhohratky vznikly z lásky k dětem a touhy vytvořit prostor, kde se mohou svobodně rozvíjet. Věříme, že každé dítě je jedinečné a zaslouží si objevovat svět vlastním způsobem. Naše aktivity jsou navrženy tak, aby podporovaly přirozenou zvídavost a kreativitu dětí."
    },
    "activities": {
        "title": "Co u nás zažijete?",
        "description": "Nabízíme širokou škálu aktivit pro děti všech věkových kategorií",
        "act1Icon": "🫧",
        "act1Color": "pink",
        "act1Title": "Sensory Boxy",
        "act1Text": "Tematické boxy plné různých textur, materiálů a překvapení na prozkoumání.",
        "act1Age": "2-6 let",
        "act2Icon": "🎨",
        "act2Color": "orange",
        "act2Title": "Kreativní tvoření",
        "act2Text": "Malování, modelování, koláže a další výtvarné techniky pro malé umělce.",
        "act2Age": "3-8 let",
        "act3Icon": "💧",
        "act3Color": "yellow",
        "act3Title": "Vodní hrátky",
        "act3Text": "Experimenty s vodou, přeléváním a objevování zákonitostí tekutin.",
        "act3Age": "1-5 let",
        "act4Icon": "🌱",
        "act4Color": "green",
        "act4Title": "Přírodní materiály",
        "act4Text": "Práce s pískem, kamínky, listy a dalšími přírodninami.",
        "act4Age": "2-7 let",
        "act5Icon": "🧩",
        "act5Color": "blue",
        "act5Title": "Montessori pomůcky",
        "act5Text": "Vzdělávací materiály pro rozvoj logiky, matematiky a jazyka.",
        "act5Age": "3-8 let",
        "act6Icon": "🎂",
        "act6Color": "purple",
        "act6Title": "Narozeninové oslavy",
        "act6Text": "Nezapomenutelné narozeniny plné her, tvoření a zábavy.",
        "act6Age": "1-10 let"
    },
    "gallery": {
        "title": "Nahlédněte do našeho světa",
        "img1Url": "",
        "img1Label": "Sensory Play",
        "img2Url": "",
        "img2Label": "Kreativní tvoření",
        "img3Url": "",
        "img3Label": "Montessori",
        "img4Url": "",
        "img4Label": "Vodní hrátky",
        "img5Url": "",
        "img5Label": "Přírodniny",
        "img6Url": "",
        "img6Label": "Oslavy"
    },
    "contact": {
        "title": "Kde nás najdete?",
        "address1": "Duhová 123",
        "address2": "Praha 1, 110 00",
        "phone": "+420 123 456 789",
        "email": "info@duhohratky.cz",
        "hours1": "Po-Pá: 9:00 - 18:00",
        "hours2": "So: 9:00 - 14:00",
        "facebook": "",
        "instagram": "",
        "youtube": ""
    },
    // Current Lessons (5 slots)
    "lessons": {
        "title": "Aktuální <span class=\"rainbow-text\">lekce</span>",
        "lesson1": {
            "active": true,
            "date": new Date().toISOString().split('T')[0],
            "time1": "14:00",
            "time2": "",
            "time3": "",
            "time4": "",
            "time5": "",
            "location": "Praha",
            "address": "",
            "price": "",
            "title": "Sensory Play: Vesmír 🚀",
            "description": "Objevování galaxie pro nejmenší.",
            "link": "#reservation",
            "tag": "free_spots"
        },
        "lesson2": {
            "active": true,
            "date": new Date(Date.now() + 86400000).toISOString().split('T')[0], // Tomorrow
            "time1": "10:00",
            "time2": "16:00",
            "time3": "",
            "time4": "",
            "time5": "",
            "location": "Brno",
            "address": "",
            "price": "",
            "title": "Montessori Dílna 🧩",
            "description": "Rozvoj samostatnosti (2-4 roky).",
            "link": "#reservation",
            "tag": "full"
        },
        "lesson3": {
            "active": true,
            "date": "",
            "time1": "15:30",
            "time2": "",
            "time3": "",
            "time4": "",
            "time5": "",
            "location": "Ostrava",
            "address": "",
            "price": "",
            "title": "Tvoření z přírodnin 🍂",
            "description": "Podzimní dekorace a listování.",
            "link": "#reservation",
            "tag": "fake_tag"
        },
        "lesson4": {
            "active": true,
            "date": "",
            "time1": "16:00",
            "time2": "17:30",
            "time3": "",
            "time4": "",
            "time5": "",
            "location": "Plzeň",
            "address": "",
            "price": "",
            "title": "Hudební hrátky 🎵",
            "description": "Rytmus a tanec pro děti.",
            "link": "#reservation",
            "tag": "fake_tag"
        },
        "lesson5": {
            "active": false,
            "date": "",
            "time1": "09:30",
            "time2": "",
            "time3": "",
            "time4": "",
            "time5": "",
            "location": "Liberec",
            "address": "",
            "price": "",
            "title": "Silvestrovské cvičení 🥂",
            "description": "Speciální novoroční lekce.",
            "link": "#reservation",
            "tag": "fake_tag"
        }
    },
    "reservio": {
        "iframeUrl": "https://duhohratky.reservio.com",
        "iframeHeight": 600,
        "phone": "+420 123 456 789"
    },
    "tips": {
        "previewTitle": "Inspirace pro domácí tvoření",
        "previewDescription": "Vyzkoušejte naše oblíbené aktivity i doma",
        "tip1Icon": "🍚",
        "tip1Category": "sensory",
        "tip1Title": "Barevná rýže",
        "tip1Description": "Jednoduchý návod na výrobu barevné senzorické rýže.",
        "tip1Time": "15 min",
        "tip1Age": "1+ rok",
        "tip1Color": "linear-gradient(135deg, #FFB6C1, #FF69B4)",
        "tip2Icon": "🥄",
        "tip2Category": "montessori",
        "tip2Title": "Přesýpání a přelévání",
        "tip2Description": "Aktivita pro rozvoj jemné motoriky.",
        "tip2Time": "10 min",
        "tip2Age": "18m+",
        "tip2Color": "linear-gradient(135deg, #FFE066, #FFD700)",
        "tip3Icon": "🍂",
        "tip3Category": "creative",
        "tip3Title": "Otisk listů",
        "tip3Description": "Krásné otisky pomocí barev a listů.",
        "tip3Time": "20 min",
        "tip3Age": "2+ roky",
        "tip3Color": "linear-gradient(135deg, #90EE90, #32CD32)"
    },
    "settings": {
        "email": "admin@duhohratky.cz",
        "seoTitle": "Duhohratky | Sensory Play & Montessori pro děti",
        "seoDescription": "Duhohratky - kreativní sensory play a Montessori aktivity pro děti. Rozvoj smyslů, motoriky a kreativity v bezpečném prostředí.",
        "seoKeywords": "sensory play, Montessori, děti, hry, rozvoj, kreativita, Duhohratky"
    }
};
