window.defaultContent = {
    "credentials": {
        "email": "admin@duhohratky.cz",
        "password": "admin123"
    },
    "hero": {
        "badge": "✨ Kreativita & Rozvoj",
        "title": "Sensory play & Montessori aktivity pro rozvoj vašich dětí",
        "titleHighlight": "",
        "subtitle": "",
        "description": "Objevte svět hravého učení, kde se děti rozvíjejí prostřednictvím smyslových her, kreativních činností a Montessori přístupu v bezpečném a inspirujícím prostředí.",
        "stat1Number": "800+",
        "stat1Label": "Šťastných dětí",
        "stat2Number": "30+",
        "stat2Label": "Uplynulých lekcí",
        "stat3Number": "5⭐",
        "stat3Label": "Hodnocení",
        "btn1Text": "📅 Rezervovat termín",
        "btn1Link": "#reservation",
        "btn2Text": "🎨 Prozkoumat aktivity",
        "btn2Link": "#activities"
    },
    "about": {
        "title": "Co jsou Duhohratky?",
        "card1Icon": "🎨",
        "card1Title": "Sensorické hraní",
        "card1Text": "Smyslové hry, které rozvíjejí hmat, čich, zrak i sluch. Děti objevují textury, barvy a zvuky v bezpečném prostředí. ",
        "card2Icon": "📚",
        "card2Title": "Montessori přístup",
        "card2Text": "Respektujeme individualitu každého dítěte. Učíme se hrou, pozorováním a vlastním tempem objevování světa.",
        "card3Icon": "🧠",
        "card3Title": "Rozvoj dovedností",
        "card3Text": "Podpora jemné motoriky, koordinace, koncentrace a kreativního myšlení prostřednictvím zábavných aktivit. Každá lekce je přitom zaměřena na konkrétní téma, ve kterém se vždy dozvědí i spoustu nových informací a rozšíří svou slovní zásobu. ",
        "card4Icon": "💕",
        "card4Title": "Bezpečné prostředí",
        "card4Text": "Materiály volíme tak, aby byly pro vaše děti bezpečné. Prostory jsou přizpůsobené potřebám malých objevitelů.",
        "storyTitle": "Jak vznikly Duhohrátky?",
        "storyText": "Duhohrátky vznikly z lásky k dětem a z touhy vytvořit prostor, kde se mohou svobodně rozvíjet.\nPřed několika lety jsem jako máma malé holčičky – a zároveň učitelka, která tehdy neměla mnoho možností seberealizace – hledala způsob, jak smysluplně trávit společný čas, učit se nové věci a růst spolu s ní. Narazila jsem na senzorické hraní, které bylo v té době v České republice teprve v začátcích. Do té doby jsem znala především Montessori prvky, které se mi velmi líbily, ale sensory play si mě naprosto získalo.\nZačala jsem doma s dcerkou postupně zkoušet různé aktivity a s radostí sledovala, jak ji baví a rozvíjejí. Naše malé pokusy se ujaly i na sociálních sítích a brzy o ně začaly projevovat zájem maminky z okolí. Postupně jsem proto začala pořádat lekce – nejprve v Jaroměři a Hradci Králové, později i v dalších městech, kam dnes pravidelně dojíždím.\nMezitím se naše rodina rozrostla o dalšího malého člena – druhou holčičku. Ani těhotenství a následná mateřská dovolená mě ale v tom, co dělám, nezastavily. Naopak mě utvrdily v tom, jak smysluplná tato práce je. Postupně se z Duhohrátek stal rodinný projekt, do kterého se zapojil i můj manžel, a dnes jsou tak nejen mojí srdeční záležitostí, ale i naší společnou cestou.\nMožná i vy hledáte místo, kde si se svým dítětem užijete kvalitní čas bez spěchu, bez tlaku na výkon a bez srovnávání. Místo, kde může být samo sebou, zkoumat, tvořit a objevovat svět vlastním tempem.\nPrávě takové prostředí se snažíme v Duhohrátkách vytvářet.\nVěříme, že každé dítě je jedinečné a zaslouží si respekt, podporu a bezpečný prostor pro růst. Naše aktivity podporují přirozenou zvídavost, kreativitu i radost z objevování. Zároveň chceme posilovat vztah mezi dětmi a rodiči a vytvářet chvíle, na které se nezapomíná.\nChceme, aby každé dítě odcházelo z Duhohrátek sebevědomější, zvídavější a šťastnější. A aby si rodiče odnášeli nejen fotografie, ale především pocit, že svému dítěti věnovali čas, který má skutečnou hodnotu.\nPokud cítíte, že je vám tento přístup blízký, budeme moc rádi, když se k nám přidáte.\nTěšíme se na vás na některé z našich lekcí."
    },
    "activities": {
        "title": "Co u nás zažijete?",
        "description": "Nabízíme širokou škálu aktivit pro děti všech věkových kategorií",
        "act1Icon": "🫧",
        "act1Color": "pink",
        "act1Title": "Sensory Boxy",
        "act1Text": "Tematické boxy plné různých textur, materiálů a překvapení na prozkoumání.",
        "act1Age": "2-6 let",
        "act2Icon": "🎨",
        "act2Color": "orange",
        "act2Title": "Kreativní tvoření",
        "act2Text": "Malování, modelování, koláže a další výtvarné techniky pro malé umělce.",
        "act2Age": "3-8 let",
        "act3Icon": "💧",
        "act3Color": "yellow",
        "act3Title": "Vodní hrátky",
        "act3Text": "Experimenty s vodou, přeléváním a objevování zákonitostí tekutin.",
        "act3Age": "1-5 let",
        "act4Icon": "🌱",
        "act4Color": "green",
        "act4Title": "Přírodní materiály",
        "act4Text": "Práce s pískem, kamínky, listy a dalšími přírodninami.",
        "act4Age": "2-7 let",
        "act5Icon": "🧩",
        "act5Color": "blue",
        "act5Title": "Montessori pomůcky",
        "act5Text": "Vzdělávací materiály pro rozvoj logiky, matematiky a jazyka.",
        "act5Age": "3-8 let",
        "act6Icon": "🎂",
        "act6Color": "purple",
        "act6Title": "Narozeninové oslavy",
        "act6Text": "Nezapomenutelné narozeniny plné her, tvoření a zábavy.",
        "act6Age": "1-10 let"
    },
    "gallery": {
        "title": "Nahlédněte do našeho světa",
        "img1Url": "",
        "img1Label": "Sensory Play",
        "img2Url": "",
        "img2Label": "Kreativní tvoření",
        "img3Url": "",
        "img3Label": "Montessori",
        "img4Url": "",
        "img4Label": "Vodní hrátky",
        "img5Url": "",
        "img5Label": "Přírodniny",
        "img6Url": "",
        "img6Label": "Oslavy"
    },
    "contact": {
        "title": "Spojme se",
        "address1": "",
        "address2": "Jasenná 229, Jasenná 552 22",
        "phone": "+420 732 159 861",
        "email": "duhohratky@seznam.cz",
        "hours1": "Po-Pá: 9:00 - 18:00",
        "hours2": "So: 9:00 - 14:00",
        "facebook": "https://www.facebook.com/duhohratky",
        "instagram": "https://instagram.com/duhohratky",
        "youtube": ""
    },
    "tips": {
        "previewTitle": "Inspirace pro domácí tvoření",
        "previewDescription": "Vyzkoušejte naše oblíbené aktivity i doma",
        "tip1Icon": "🍚",
        "tip1Category": "sensory",
        "tip1Title": "Barevná rýže",
        "tip1Description": "Jednoduchý návod na výrobu barevné senzorické rýže.",
        "tip1Time": "15 min",
        "tip1Age": "1+ rok",
        "tip1Color": "linear-gradient(135deg, #FFB6C1, #FF69B4)",
        "tip2Icon": "🥄",
        "tip2Category": "montessori",
        "tip2Title": "Přesýpání a přelévání",
        "tip2Description": "Aktivita pro rozvoj jemné motoriky.",
        "tip2Time": "10 min",
        "tip2Age": "18m+",
        "tip2Color": "linear-gradient(135deg, #FFE066, #FFD700)",
        "tip3Icon": "🍂",
        "tip3Category": "creative",
        "tip3Title": "Otisk listů",
        "tip3Description": "Krásné otisky pomocí barev a listů.",
        "tip3Time": "20 min",
        "tip3Age": "2+ roky",
        "tip3Color": "linear-gradient(135deg, #90EE90, #32CD32)"
    },
    "reservio": {
        "iframeUrl": "https://www.reservideo.com/booking/iframe/duhohratky",
        "iframeHeight": "600",
        "phone": "+420 732 159 861"
    },
    "upcoming": {
        "title": "Připravujeme další témata",
        "description": "Na jaké další lekce se můžete v nejbližší době těšit?",
        "visible": true,
        "items": {
            "0": {
                "active": true,
                "icon": "🐣",
                "title": "Velikonoce",
                "description": "vejce kuře pomlázka nnnn"
            },
            "1": {
                "active": false,
                "icon": "🚒",
                "title": "Téma 2",
                "description": "Popis tématu 2"
            },
            "2": {
                "active": false,
                "icon": "🦕",
                "title": "Téma 3",
                "description": "Popis tématu 3"
            }
        }
    },
    "lessons": {
        "title": "Aktuální <span class=\"rainbow-text\">lekce</span>",
        "lesson1": {
            "active": true,
            "title": "<span class=\"rainbow-text\">Animované pohádky</span>",
            "location": "Hradec Králové",
            "date": "2026-02-19",
            "tag": "free_spots",
            "description": "Tlapková patrola, Blesk McQueen, Krteček, Ledové Království, Bing, Prasátko Peppa a další",
            "link": "#reservation",
            "time1": "10:00",
            "time2": "15:00",
            "time3": "16:30",
            "address": "Centrům Budulínek - Průmyslová 1198",
            "price": "250 Kč"
        },
        "lesson2": {
            "active": true,
            "title": "<span class=\"rainbow-text\">Animované pohádky</span>",
            "location": "Chlumec nad Cidlinou",
            "date": "2026-02-20",
            "tag": "free_spots",
            "link": "#reservation",
            "description": "Tlapková patrola, Blesk McQueen, Krteček, Ledové Království, Bing, Prasátko Peppa a další",
            "time1": "10:00",
            "price": "250 Kč",
            "address": "Sokolovna - Kozelkova 266, 1. patro"
        },
        "lesson3": {
            "active": true,
            "title": "<span class=\"rainbow-text\">Animované pohádky</span>",
            "location": "Náchod",
            "date": "2026-02-23",
            "tag": "free_spots",
            "description": "Tlapková patrola, Blesk McQueen, Krteček, Ledové Království, Bing, Prasátko Peppa a další",
            "link": "#reservation",
            "time1": "16:00",
            "price": "250 Kč",
            "address": "MC Hopsáček - Zelená 157"
        },
        "lesson4": {
            "active": true,
            "title": "<span class=\"rainbow-text\">Animované pohádky</span>",
            "location": "Jaroměř",
            "date": "2026-02-23",
            "tag": "free_spots",
            "description": "Tlapková patrola, Blesk McQueen, Krteček, Ledové Království, Bing, Prasátko Peppa a další",
            "link": "#reservation",
            "price": "250 Kč",
            "time1": "10:00",
            "address": "Školní 95, Josefov"
        },
        "lesson5": {
            "active": true,
            "title": "<span class=\"rainbow-text\">Animované pohádky</span>",
            "location": "Jasenná",
            "date": "2026-02-24",
            "tag": "free_spots",
            "description": "Tlapková patrola, Blesk McQueen, Krteček, Ledové Království, Bing, Prasátko Peppa a další",
            "link": "#reservation",
            "price": "250 Kč",
            "time1": "15:00",
            "address": "Jasenná 229, Jasenná",
            "time2": "16:30"
        }
    },
    "settings": {
        "email": "admin@duhohratky.cz",
        "seoTitle": "Duhohratky | Sensory Play & Montessori pro děti",
        "seoDescription": "Duhohratky - kreativní sensory play a Montessori aktivity pro děti. Rozvoj smyslů, motoriky a kreativity v bezpečném prostředí.",
        "seoKeywords": "sensory play, Montessori, děti, hry, rozvoj, kreativita, Duhohratky"
    }
};